# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f51dd1ef5fbf2ba8048b45efae1f2e92bbbf1ffb9b8e3a4675caf7441a43e22a5637aee18edd98935ad7e2cd50ee48f460712dafa09cf834755b64f581d26b0

test:
  secret_key_base: 56bcdaf42bd00fd1998413eec50f3f521fb5ceac92513a24f902c97122ff4f0366b9a447c41531f35326b8c287b4e5a347f1cc723ca9830c9fc96e1f004f3792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
